#######################################
# MIT License
# Copyright (c) 2022 Shinya Oguri
# https://github.com/shinyaoguri/setup
#######################################
- hosts: localhost
  connection: local
  vars:
    homebrew_taps:
      - homebrew/cask
      - homebrew/cask-fonts
    ###############
    # CUI App List
    ###############
    homebrew_packages:
      # バージョン管理関係
      - name: git
      # エディタ関係
      - name: wget
      # シェル関係
      - name: zsh
      - name: starship
      - name: tree
      - name: trash
      - name: ghq
  tasks:
    ##########
    # Homebrew
    ##########
    - name: setup homebrew
      ignore_errors: yes
      block:
        - name: homebrew update
          homebrew:
            update_homebrew: yes
        - name: homebrew tap
          homebrew_tap:
            name: '{{ item }}'
            state: present
          with_items: '{{ homebrew_taps }}'
        - name: homebrew packages install
          homebrew:
            name: '{{ item.name }}'
            state: '{{ item.state | default("present") }}'
          with_items: '{{ homebrew_packages }}'
      
      
    ##########
    # AppStore
    ##########
    - name: install from AppStore
      ignore_errors: yes
      block:
        - name: brew install mas
          homebrew:
            name: mas
            state: present            
        - name: fetch list
          command: mas list
          register: installed_list
          check_mode: no
          changed_when: no
        - name: install from AppStore
          command: "mas install {{ item.id }}"
          when: "installed_list.stdout_lines | select('search', item.id) | list | length == 0"
          loop: "{{ apps }}"
      
    ####################
    # Download dotfiles
    ####################
    - name: setup dotfiles
      ignore_errors: yes
      block:
        - name: git clone dotfiles
          ansible.builtin.git:
            repo: git@github.com:shusaid/dotfiles.git
            dest: '{{ ansible_env.HOME }}/src/github.com/shusaid/dotfiles'
        - name: .config/zsh mkdir
          file:
            path: '{{ ansible_env.HOME}}/.config/zsh'
            state: directory
        - name: zsh config symlinks
          file:
            src: '{{ ansible_env.HOME}}/dotfiles/config.zsh'
            dest: '{{ ansible_env.HOME}}/.config/fish/config.zsh'
            state: link
            force: yes
    ###############
    # Homebrew Cask
    ###############
    - name: homebrew cask packages install
      ignore_errors: yes
      community.general.homebrew_cask: name={{ item.name }} state=installed
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'
          
    ###################
    # Zsh Setup
    ###################
    - name: zsh setup
      block:
        - name: set homebrew-zsh default
          become: true
          lineinfile:
            path: /etc/shells
            regexp: '/opt/homebrew/bin/zsh'
            insertafter: '/bin/zsh'
            line: '/opt/homebrew/bin/zsh'    
        - name: set zsh as default
          become: true
          user:
            name: "{{ ansible_user_id }}"
            shell: /opt/homebrew/bin/zsh
    # anyenv
    - name: setup anyenv
      block:
        - name: anyenv setting
          file:
            path: '{{ ansible_env.HOME }}/.anyenv/plugins'
            state: directory
        - name: anyenv-update clone
          ansible.builtin.git:
            repo: https://github.com/znz/anyenv-update.git
            dest: '{{ ansible_env.HOME }}/.anyenv/plugins/anyenv-update'
